library(data.table)
library(here)
library(tidyverse)
library(purrr)
library(umx)
library(OpenMx)
library(psych)
library(labelled)
library(dplyr)
library(dtplyr)

setwd("N:/durable/projects/class")

regoccimerge <- readRDS("N:/durable/projects/class/01 - Data/regoccimerge_all.rds")

# Create Treiman ----------------------------------------------------------

# Scipt Harry Ganzeboom: www.harryganzeboom.nl/isco88/

regoccimerge <- mutate(regoccimerge, isco88 = ifelse(startsWith(isco88, "00"), NA, isco88))
regoccimerge <- mutate(regoccimerge, isco88 = ifelse(isco88 == "0", NA, isco88))
regoccimerge <- mutate(regoccimerge, isco88 = ifelse(isco88 == "-2-2", NA, isco88))

regoccimerge <- mutate(regoccimerge, trei = ifelse(isco88 == 1000, 51, NA))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1000, 51, NA))


regoccimerge <- lazy_dt(regoccimerge)

regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1100,67, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1110,64, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1120,71, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1130,63, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1140,63, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1141,63, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1142,63, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1143,63, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1200,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1210,70, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1220,63, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1221,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1222,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1223,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1224,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1225,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1226,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1227,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1228,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1229,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1230,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1231,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1232,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1233,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1234,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1235,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1236,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1237,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1239,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1240,55, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1250,65, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1251,73, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1252,63, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1300,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1310,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1311,47, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1312,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1313,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1314,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1315,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1316,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1317,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1318,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 1319,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2000,62, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2100,63, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2110,69, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2111,75, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2112,72, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2113,69, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2114,67, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2120,56, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2121,69, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2122,55, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2130,51, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2131,51, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2132,51, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2139,51, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2140,63, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2141,72, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2142,70, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2143,65, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2144,65, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2145,66, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2146,66, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2147,61, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2148,58, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2149,56, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2200,70, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2210,62, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2211,69, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2212,68, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2213,56, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2220,73, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2221,78, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2222,70, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2223,61, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2224,64, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2229,73, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2230,54, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2300,61, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2310,78, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2320,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2321,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2322,57, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2330,57, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2331,57, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2332,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2340,62, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2350,62, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2351,68, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2352,68, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2359,62, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2400,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2410,57, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2411,62, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2412,56, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2419,57, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2420,73, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2421,73, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2422,76, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2429,71, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2430,54, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2431,54, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2432,54, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2440,58, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2441,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2442,67, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2443,67, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2444,62, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2445,67, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2446,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2450,57, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2451,58, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2452,57, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2453,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2454,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2455,57, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 2460,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3000,48, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3100,48, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3110,47, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3111,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3112,39, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3113,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3114,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3115,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3116,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3117,53, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3118,55, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3119,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3120,53, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3121,53, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3122,53, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3123,53, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3130,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3131,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3132,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3133,58, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3139,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3140,57, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3141,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3142,55, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3143,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3144,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3145,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3150,54, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3151,54, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3152,54, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3200,51, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3210,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3211,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3212,47, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3213,55, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3220,51, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3221,53, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3222,48, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3223,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3224,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3225,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3226,51, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3227,48, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3228,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3229,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3230,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3231,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3232,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3240,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3241,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3242,22, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3300,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3310,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3320,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3330,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3340,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3400,48, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3410,47, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3411,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3412,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3413,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3414,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3415,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3416,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3417,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3419,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3420,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3421,55, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3422,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3423,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3429,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3430,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3431,53, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3432,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3433,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3434,51, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3439,53, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3440,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3441,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3442,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3443,55, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3444,54, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3449,55, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3450,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3451,60, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3452,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3460,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3470,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3471,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3472,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3473,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3474,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3475,49, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 3480,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4000,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4100,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4110,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4111,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4112,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4113,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4114,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4115,53, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4120,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4121,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4122,36, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4130,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4131,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4132,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4133,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4140,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4141,36, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4142,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4143,41, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4144,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4190,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4200,39, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4210,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4211,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4212,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4213,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4214,15, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4215,27, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4220,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4221,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4222,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 4223,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5000,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5100,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5110,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5111,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5112,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5113,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5120,26, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5121,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5122,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5123,21, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5130,27, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5131,23, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5132,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5133,17, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5139,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5140,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5141,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5142,17, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5143,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5149,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5150,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5151,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5152,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5160,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5161,35, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5162,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5163,39, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5164,39, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5169,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5200,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5210,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5220,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 5230,24, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6000,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6100,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6110,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6111,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6112,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6113,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6114,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6120,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6121,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6122,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6123,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6124,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6129,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6130,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6131,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6132,41, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6133,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6134,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6140,24, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6141,24, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6142,16, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6150,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6151,23, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6152,23, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6153,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6154, 6, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6200,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 6210,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7000,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7100,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7110,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7111,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7112,36, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7113,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7120,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7121,36, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7122,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7123,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7124,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7129,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7130,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7131,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7132,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7133,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7134,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7135,26, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7136,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7137,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7140,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7141,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7142,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7143,20, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7200,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7210,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7211,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7212,39, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7213,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7214,44, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7215,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7216,26, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7220,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7221,35, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7222,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7223,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7224,27, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7230,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7231,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7232,50, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7233,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7234,20, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7240,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7241,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7242,48, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7243,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7244,35, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7245,36, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7300,39, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7310,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7311,47, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7312,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7313,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7320,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7321,25, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7322,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7323,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7324,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7330,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7331,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7332,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7340,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7341,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7342,41, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7343,41, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7344,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7345,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7346,52, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7400,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7410,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7411,24, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7412,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7413,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7414,35, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7415,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7416,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7420,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7421,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7422,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7423,36, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7424,21, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7430,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7431,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7432,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7433,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7434,35, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7435,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7436,26, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7437,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7440,27, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7441,22, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7442,27, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7500,48, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7510,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7520,46, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 7530,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8000,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8100,36, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8110,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8111,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8112,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8113,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8120,40, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8121,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8122,36, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8123,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8124,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8130,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8131,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8139,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8140,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8141,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8142,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8143,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8150,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8151,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8152,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8153,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8154,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8155,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8159,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8160,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8161,42, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8162,35, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8163,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8170,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8171,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8172,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8200,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8210,37, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8211,38, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8212,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8220,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8221,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8222,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8223,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8224,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8229,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8230,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8231,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8232,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8240,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8250,41, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8251,41, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8252,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8253,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8260,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8261,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8262,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8263,25, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8264,25, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8265,26, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8266,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8269,26, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8270,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8271,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8272,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8273,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8274,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8275,35, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8276,45, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8277,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8278,34, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8279,39, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8280,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8281,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8282,48, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8283,48, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8284,30, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8285,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8286,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8290,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8300,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8310,36, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8311,43, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8312,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8320,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8321,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8322,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8323,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8324,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8330,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8331,31, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8332,32, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8333,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8334,28, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8340,29, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 8400,33, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9000,21, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9100,23, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9110,25, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9111,24, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9112,24, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9113,26, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9120,12, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9130,21, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9131,22, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9132,21, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9133,22, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9140,23, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9141,25, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9142,19, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9150,20, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9151,22, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9152,20, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9153,21, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9160,13, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9161,13, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9162,13, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9200,23, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9210,23, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9211,23, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9212,18, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9213,23, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9300,18, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9310,16, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9311,18, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9312,15, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9313,15, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9320,19, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9321,18, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9322,22, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9330,20, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9331,17, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9332,22, trei))
regoccimerge <- mutate(regoccimerge, trei = ifelse (isco88 == 9333,20, trei))

regoccimerge <- as_tibble(regoccimerge)

# Create treiman imp----------------------------------------------------------


regoccimerge <- lazy_dt(regoccimerge)

regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1100,67, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1110,64, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1120,71, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1130,63, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1140,63, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1141,63, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1142,63, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1143,63, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1200,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1210,70, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1220,63, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1221,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1222,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1223,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1224,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1225,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1226,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1227,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1228,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1229,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1230,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1231,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1232,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1233,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1234,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1235,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1236,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1237,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1239,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1240,55, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1250,65, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1251,73, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1252,63, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1300,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1310,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1311,47, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1312,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1313,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1314,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1315,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1316,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1317,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1318,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 1319,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2000,62, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2100,63, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2110,69, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2111,75, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2112,72, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2113,69, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2114,67, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2120,56, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2121,69, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2122,55, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2130,51, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2131,51, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2132,51, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2139,51, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2140,63, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2141,72, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2142,70, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2143,65, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2144,65, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2145,66, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2146,66, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2147,61, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2148,58, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2149,56, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2200,70, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2210,62, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2211,69, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2212,68, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2213,56, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2220,73, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2221,78, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2222,70, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2223,61, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2224,64, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2229,73, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2230,54, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2300,61, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2310,78, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2320,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2321,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2322,57, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2330,57, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2331,57, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2332,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2340,62, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2350,62, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2351,68, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2352,68, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2359,62, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2400,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2410,57, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2411,62, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2412,56, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2419,57, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2420,73, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2421,73, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2422,76, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2429,71, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2430,54, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2431,54, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2432,54, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2440,58, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2441,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2442,67, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2443,67, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2444,62, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2445,67, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2446,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2450,57, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2451,58, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2452,57, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2453,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2454,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2455,57, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 2460,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3000,48, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3100,48, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3110,47, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3111,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3112,39, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3113,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3114,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3115,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3116,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3117,53, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3118,55, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3119,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3120,53, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3121,53, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3122,53, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3123,53, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3130,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3131,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3132,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3133,58, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3139,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3140,57, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3141,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3142,55, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3143,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3144,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3145,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3150,54, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3151,54, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3152,54, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3200,51, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3210,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3211,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3212,47, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3213,55, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3220,51, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3221,53, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3222,48, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3223,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3224,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3225,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3226,51, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3227,48, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3228,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3229,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3230,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3231,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3232,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3240,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3241,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3242,22, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3300,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3310,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3320,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3330,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3340,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3400,48, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3410,47, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3411,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3412,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3413,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3414,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3415,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3416,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3417,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3419,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3420,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3421,55, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3422,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3423,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3429,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3430,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3431,53, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3432,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3433,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3434,51, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3439,53, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3440,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3441,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3442,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3443,55, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3444,54, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3449,55, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3450,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3451,60, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3452,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3460,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3470,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3471,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3472,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3473,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3474,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3475,49, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 3480,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4000,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4100,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4110,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4111,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4112,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4113,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4114,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4115,53, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4120,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4121,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4122,36, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4130,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4131,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4132,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4133,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4140,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4141,36, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4142,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4143,41, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4144,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4190,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4200,39, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4210,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4211,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4212,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4213,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4214,15, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4215,27, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4220,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4221,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4222,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 4223,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5000,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5100,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5110,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5111,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5112,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5113,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5120,26, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5121,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5122,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5123,21, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5130,27, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5131,23, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5132,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5133,17, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5139,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5140,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5141,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5142,17, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5143,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5149,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5150,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5151,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5152,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5160,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5161,35, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5162,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5163,39, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5164,39, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5169,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5200,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5210,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5220,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 5230,24, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6000,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6100,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6110,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6111,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6112,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6113,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6114,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6120,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6121,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6122,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6123,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6124,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6129,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6130,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6131,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6132,41, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6133,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6134,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6140,24, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6141,24, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6142,16, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6150,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6151,23, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6152,23, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6153,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6154, 6, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6200,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 6210,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7000,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7100,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7110,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7111,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7112,36, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7113,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7120,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7121,36, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7122,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7123,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7124,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7129,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7130,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7131,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7132,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7133,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7134,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7135,26, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7136,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7137,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7140,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7141,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7142,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7143,20, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7200,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7210,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7211,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7212,39, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7213,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7214,44, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7215,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7216,26, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7220,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7221,35, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7222,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7223,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7224,27, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7230,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7231,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7232,50, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7233,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7234,20, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7240,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7241,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7242,48, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7243,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7244,35, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7245,36, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7300,39, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7310,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7311,47, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7312,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7313,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7320,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7321,25, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7322,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7323,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7324,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7330,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7331,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7332,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7340,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7341,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7342,41, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7343,41, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7344,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7345,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7346,52, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7400,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7410,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7411,24, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7412,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7413,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7414,35, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7415,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7416,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7420,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7421,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7422,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7423,36, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7424,21, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7430,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7431,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7432,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7433,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7434,35, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7435,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7436,26, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7437,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7440,27, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7441,22, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7442,27, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7500,48, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7510,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7520,46, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 7530,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8000,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8100,36, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8110,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8111,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8112,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8113,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8120,40, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8121,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8122,36, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8123,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8124,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8130,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8131,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8139,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8140,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8141,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8142,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8143,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8150,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8151,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8152,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8153,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8154,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8155,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8159,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8160,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8161,42, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8162,35, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8163,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8170,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8171,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8172,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8200,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8210,37, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8211,38, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8212,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8220,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8221,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8222,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8223,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8224,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8229,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8230,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8231,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8232,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8240,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8250,41, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8251,41, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8252,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8253,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8260,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8261,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8262,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8263,25, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8264,25, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8265,26, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8266,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8269,26, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8270,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8271,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8272,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8273,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8274,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8275,35, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8276,45, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8277,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8278,34, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8279,39, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8280,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8281,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8282,48, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8283,48, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8284,30, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8285,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8286,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8290,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8300,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8310,36, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8311,43, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8312,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8320,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8321,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8322,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8323,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8324,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8330,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8331,31, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8332,32, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8333,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8334,28, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8340,29, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 8400,33, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9000,21, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9100,23, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9110,25, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9111,24, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9112,24, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9113,26, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9120,12, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9130,21, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9131,22, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9132,21, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9133,22, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9140,23, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9141,25, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9142,19, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9150,20, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9151,22, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9152,20, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9153,21, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9160,13, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9161,13, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9162,13, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9200,23, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9210,23, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9211,23, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9212,18, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9213,23, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9300,18, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9310,16, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9311,18, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9312,15, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9313,15, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9320,19, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9321,18, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9322,22, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9330,20, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9331,17, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9332,22, treiimp))
regoccimerge <- mutate(regoccimerge, treiimp = ifelse(yrke_imp == 9333,20, treiimp))

regoccimerge <- as_tibble(regoccimerge)

table(regoccimerge$trei)
table(regoccimerge$treiimp)

regoccimerge <- mutate(regoccimerge, trei = ifelse(is.na(trei), treiimp, trei))

regoccimerge <- select(regoccimerge, -treiimp)


# Missing codes

miss <- filter(regoccimerge, is.na(regoccimerge$trei))
tab <- miss %>% group_by(Year, isco88) %>% summarize(freq=n())
write.table(tab, "03 - Results/treimiss.txt")
rm(tab, miss)

# Keeping occupation at age 50

regoccimerge <- select(regoccimerge, -kjoenn, -BU, -decile, -Income)

regoccimerge <- filter(regoccimerge, foedselsaar > 1940 & foedselsaar < 1981)

regoccimerge$age <- regoccimerge$Year - regoccimerge$foedselsaar
regoccimerge <- filter(regoccimerge, age < 63)
regoccimerge$dev <- regoccimerge$age - 50
regoccimerge$dev <- abs(regoccimerge$dev)

regoccimerge <- lazy_dt(regoccimerge)

regoccimerge = regoccimerge %>% 
  arrange(w18_0590_lopenr_person, dev) %>% 
  group_by(w18_0590_lopenr_person) %>%
  mutate(trei50 = first(na.omit(trei))) %>% 
  ungroup()

regoccimerge = regoccimerge %>% 
  arrange(w18_0590_lopenr_person, dev) %>% 
  group_by(w18_0590_lopenr_person) %>%
  mutate(devtrei = case_when(trei50 == trei ~ dev)) %>% 
  ungroup()

regoccimerge = regoccimerge %>% 
  arrange(w18_0590_lopenr_person, devtrei) %>% 
  group_by(w18_0590_lopenr_person) %>%
  mutate(devtrei = first(na.omit(devtrei))) %>% 
  ungroup()

regoccimerge <- as_tibble(regoccimerge)

saveRDS(regoccimerge, "N:/durable/projects/class/01 - Data/Trei.rds")

# Twin data ---------------------------------------------------------------

twins <- fread("N:/durable/prepared/twin-linked-nodups.csv")
nrow(twins)
names(twins)

twins <- select(twins, w18_0590_lopenr_person, Zygo, tvilling_par_ID, kjoenn)
occ <- select(regoccimerge, w18_0590_lopenr_person, foedselsaar, trei50, devtrei)
occ <- distinct(occ)

occtwins <- inner_join(twins, occ, by = "w18_0590_lopenr_person")

occtwins <- occtwins %>%                                     ## twins_utfall hvis vi ikke skal kaste ut dem som er gift 
  mutate(twinpair = floor(tvilling_par_ID/10)) %>% 
  mutate(twinno = tvilling_par_ID-(twinpair*10)) %>%
  arrange(twinpair) %>%
  group_by(twinpair) %>%
  mutate(ant_tvilling = n()) %>% 
  filter(ant_tvilling==2) %>%  #beholder bare der begge tvillinger er representert
  mutate(sexcomb = case_when(var(kjoenn)==0 & kjoenn==1 ~ "Males",
                             var(kjoenn)==0 & kjoenn==2 ~ "Females",
                             TRUE ~ "Mixed")) %>% 
  filter(sexcomb!="Mixed") %>% 
  select(twinpair, twinno, Zygo, foedselsaar, sexcomb, trei50, devtrei, ant_tvilling)

occtwins_wide <- occtwins %>%
  group_by(twinpair) %>%
  gather(key=var, value=info, trei50, devtrei) %>%
  mutate(var = str_c(var,twinno)) %>%
  select(-twinno) %>%
  spread(key=var, value=info)

write.csv(occtwins,"N:/durable/projects/class/01 - Data/Treitwins.csv", row.names = FALSE)
write.csv(occtwins_wide,"N:/durable/projects/class/01 - Data/Treitwins_wide.csv", row.names = FALSE)

occtwins <- occtwins_wide
rm(occtwins_wide, regoccimerge, occ, twins)
occtwins <- data.frame(occtwins)

# General twin analyses ---------------------------------------------------------------

mztrei <- na.omit(subset(occtwins, Zygo ==  1))
dztrei <- na.omit(subset(occtwins, Zygo ==  2))
mztrei <- data.frame(mztrei)
dztrei <- data.frame(dztrei)

#ACE model
m1 <- umxACE(selDVs = c("trei50"), selCov = "devtrei", sep = "", dzData = dztrei, mzData = mztrei, bound = NULL, intervals = TRUE)
umxSummary(m1)

umxConfint(m1, parm = c("top.A_std", "top.C_std", "top.E_std", "top.A", "top.C", "top.E"), 
           run = TRUE, showErrorCodes = TRUE)


# Models per gender -------------------------------------------------------

mztreiman <- filter(mztrei, sexcomb == "Males")
dztreiman <- filter(dztrei, sexcomb == "Males")
mztreiwoman <- filter(mztrei, sexcomb == "Females")
dztreiwoman <- filter(dztrei, sexcomb == "Females")

# Ordinal models

m1man <- umxACE(selDVs = c("trei50"), selCov = "devtrei", sep = "", dzData = dztreiman, mzData = mztreiman, intervals = TRUE)
umxSummary(m1man)

umxConfint(m1man, parm = c("top.A_std", "top.C_std", "top.E_std", "top.A", "top.C", "top.E"), 
           run = TRUE, showErrorCodes = TRUE)

m1woman <- umxACE(selDVs = c("trei50"), selCov = "devtrei", sep = "", dzData = dztreiwoman, mzData = mztreiwoman, bound = NULL, intervals = TRUE)
umxSummary(m1woman)

umxConfint(m1woman, parm = c("top.A_std", "top.C_std", "top.E_std", "top.A", "top.C", "top.E"), 
           run = TRUE, showErrorCodes = TRUE)


# Models per age ----------------------------------------------------------

mztreiung <- filter(mztrei, foedselsaar > 1960)
dztreiung <- filter(dztrei, foedselsaar > 1960)
mztreigaml <- filter(mztrei, foedselsaar < 1961)
dztreigaml <- filter(dztrei, foedselsaar < 1961)

# Ordinal models

m1ung <- umxACE(selDVs = c("trei50"), selCov = "devtrei", sep = "", dzData = dztreiung, mzData = mztreiung, intervals = TRUE)
umxSummary(m1ung)

umxConfint(m1ung, parm = c("top.A_std", "top.C_std", "top.E_std", "top.A", "top.C", "top.E"), 
           run = TRUE, showErrorCodes = TRUE)

m1gaml <- umxACE(selDVs = c("trei50"), selCov = "devtrei", sep = "", dzData = dztreigaml, mzData = mztreigaml, bound = NULL, intervals = TRUE)
umxSummary(m1gaml)

umxConfint(m1gaml, parm = c("top.A_std", "top.C_std", "top.E_std", "top.A", "top.C", "top.E"), 
           run = TRUE, showErrorCodes = TRUE)




